services:
  # Flask Backend API
  dss-backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: dss-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - DATABASE_URL=sqlite:///data/dss.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - dss-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # React Frontend
  dss-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dss-frontend
    ports:
      - "3000:80"
    depends_on:
      - dss-backend
    networks:
      - dss-network
    restart: unless-stopped

  # Nginx API Gateway and Load Balancer
  nginx:
    image: nginx:alpine
    container_name: dss-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - dss-backend
      - dss-frontend
    networks:
      - dss-network
    restart: unless-stopped

networks:
  dss-network:
    driver: bridge
